# syntax=docker/dockerfile:1
FROM node:22-alpine AS base
WORKDIR /src
RUN chown -R node:node /src && chmod -R 770 /src

# --- development for local ---
FROM base AS development
COPY ["package.json", "pnpm-lock.yaml", "./"]
# キャッシュディレクトリを指定
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
COPY . .
EXPOSE 3000
ENTRYPOINT ["pnpm", "run", "dev"]
