import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MswProvider } from "../../providers/msw-provider";
import TanstackProvider from "../../providers/tanstack-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanstackProvider>
          <MswProvider>
            <ul>
              <li><a href="/">ホーム</a></li>
              <li><a href="/form">入力フォーム</a></li>
            </ul>
            {children}
          </MswProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
