/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */
import {
  z as zod
} from 'zod';

/**
 * Get all notices
 * @summary Retrive all notices
 */
export const noticesServiceGetNoticesQueryParams = zod.object({
  "page": zod.number().optional(),
  "limit": zod.number().optional()
})

export const noticesServiceGetNotices200ResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string(),
  "released_at": zod.string().date(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})
export const noticesServiceGetNotices200Response = zod.array(noticesServiceGetNotices200ResponseItem)

export const noticesServiceGetNotices400Response = zod.object({
  "code": zod.enum(['BAD_REQUEST']),
  "message": zod.string()
})

export const noticesServiceGetNotices500Response = zod.object({
  "code": zod.enum(['INTERNAL_SERVER_ERROR']),
  "message": zod.string()
})


/**
 * Get a specific notice by ID
 * @summary Retrice a notice by ID
 */
export const noticesServiceGetNoticeParams = zod.object({
  "id": zod.string()
})

export const noticesServiceGetNotice200Response = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string(),
  "released_at": zod.string().date(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

export const noticesServiceGetNotice400Response = zod.object({
  "code": zod.enum(['BAD_REQUEST']),
  "message": zod.string()
})

export const noticesServiceGetNotice404Response = zod.object({
  "code": zod.enum(['NOT_FOUND']),
  "message": zod.string()
})

export const noticesServiceGetNotice500Response = zod.object({
  "code": zod.enum(['INTERNAL_SERVER_ERROR']),
  "message": zod.string()
})
