/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */
import type { BadRequestErrorCode } from './badRequestErrorCode';

export interface BadRequestError {
  code: BadRequestErrorCode;
  message: string;
}
