/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */

export type BadRequestErrorCode =
  (typeof BadRequestErrorCode)[keyof typeof BadRequestErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BadRequestErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
} as const;
