/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */

export type InternalServerErrorCode =
	(typeof InternalServerErrorCode)[keyof typeof InternalServerErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InternalServerErrorCode = {
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
