/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */

<<<<<<< HEAD
export type NotFoundErrorCode =
  (typeof NotFoundErrorCode)[keyof typeof NotFoundErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotFoundErrorCode = {
  NOT_FOUND: "NOT_FOUND",
=======
export type NotFoundErrorCode = (typeof NotFoundErrorCode)[keyof typeof NotFoundErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotFoundErrorCode = {
	NOT_FOUND: 'NOT_FOUND',
>>>>>>> main
} as const;
