/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */

export type NoticesServiceGetNoticesParams = {
<<<<<<< HEAD
  page?: number;
  limit?: number;
=======
	page?: number;
	limit?: number;
>>>>>>> main
};
