/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */

export interface Notice {
  id: number;
  title: string;
  content: string;
  released_at: string;
  created_at: string;
  updated_at: string;
}
