/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notice Service
 * OpenAPI spec version: 0.0.0
 */
import type { ValidationError } from './validationError';

export interface SDDServiceValidationErrorResponse {
	/** The body type of the operation request or response. */
	body: ValidationError;
}
